config/routes.rb
Rails.application.routes.draw do
  resources :pupils

end

app/models/pupil.rb
class Pupil < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
  before_action :set_pupil, only: [:show, :edit, :update, :destroy]

  # GET /pupils
  # GET /pupils.json
  def index
    @pupils = Pupil.all
  end

  # GET /pupils/1
  # GET /pupils/1.json
  def show
  end

  # GET /pupils/new
  def new
    @pupil = Pupil.new
  end

  # GET /pupils/1/edit
  def edit
  end

  # POST /pupils
  # POST /pupils.json
  def create
    @pupil = Pupil.new(pupil_params)

    respond_to do |format|
      if @pupil.save
        format.html { redirect_to @pupil, notice: 'Pupil was successfully created.' }
        format.json { render :show, status: :created, location: @pupil }
      else
        format.html { render :new }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pupils/1
  # PATCH/PUT /pupils/1.json
  def update
    respond_to do |format|
      if @pupil.update(pupil_params)
        format.html { redirect_to @pupil, notice: 'Pupil was successfully updated.' }
        format.json { render :show, status: :ok, location: @pupil }
      else
        format.html { render :edit }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupils/1
  # DELETE /pupils/1.json
  def destroy
    @pupil.destroy
    respond_to do |format|
      format.html { redirect_to pupils_url, notice: 'Pupil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pupil
      @pupil = Pupil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pupil_params
      params.require(:pupil).permit(:vorname, :nachname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pupils/_form.html.erb
<%= form_for(@pupil) do |f| %>
  <% if @pupil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pupil.errors.count, "error") %> prohibited this pupil from being saved:</h2>

      <ul>
      <% @pupil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vorname %><br>
    <%= f.text_field :vorname %>
  </div>
  <div class="field">
    <%= f.label :nachname %><br>
    <%= f.text_field :nachname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pupils/edit.html.erb
<h1>Editing Pupil</h1>

<%= render 'form' %>

<%= link_to 'Show', @pupil %> |
<%= link_to 'Back', pupils_path %>

app/views/pupils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pupils</h1>

<table>
  <thead>
    <tr>
      <th>Vorname</th>
      <th>Nachname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pupils.each do |pupil| %>
      <tr>
        <td><%= pupil.vorname %></td>
        <td><%= pupil.nachname %></td>
        <td><%= link_to 'Show', pupil %></td>
        <td><%= link_to 'Edit', edit_pupil_path(pupil) %></td>
        <td><%= link_to 'Destroy', pupil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pupil', new_pupil_path %>

app/views/pupils/new.html.erb
<h1>New Pupil</h1>

<%= render 'form' %>

<%= link_to 'Back', pupils_path %>

app/views/pupils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vorname:</strong>
  <%= @pupil.vorname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @pupil.nachname %>
</p>

<%= link_to 'Edit', edit_pupil_path(@pupil) %> |
<%= link_to 'Back', pupils_path %>